core/urls.py
from django.contrib import admin
from django.urls import path, include


from core.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name='login'),
    path('veterinaria/', include('veterinaria.urls', namespace='home'))
]

veterinaria/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from core.views import HomeView
from .views import ReservaMedicaCreateView, ReservaMedicaListView, ReservaMedicaUpdateView, ReservaMedicaDeleteView
from core.views import FuncionariosView, InventarioView, LoginView
app_name = 'veterinaria'

urlpatterns = [
    path('',HomeView.as_view(), name='home' ),
    path('reservasmedicas/', ReservaMedicaListView.as_view(), name='reservasmedicas' ),
    path('reservasmedicas/create/', ReservaMedicaCreateView.as_view(), name='reservasmedicascreate' ),
    path('reservasmedicas/<int:pk>/reservasmedicasupdate/', ReservaMedicaUpdateView.as_view(), name='reservasmedicasupdate'),
    path('reservasmedicas/<int:pk>/reservasmedicasdelete/', ReservaMedicaDeleteView.as_view(), name='reservasmedicasdelete'),
    path('funcionarios/', FuncionariosView.as_view(), name='funcionarios'),
    path('inventario/', InventarioView.as_view(), name='inventario'),
    path('cerrarsesion/', LoginView.as_view(), name='cerrarsesion')

]

urlpatterns += staticfiles_urlpatterns()

veterinaria/models.py
from django.db import models

# Create your models here.

class UserAccount(models.Model):
    user = models.CharField(max_length=10)
    password = models.CharField(max_length=10)

    def __str__(self):
        return self.user

class ReservaMedica(models.Model):
    nombreCliente = models.TextField()
    apellidoCliente = models.TextField()
    rutCliente = models.TextField()
    telefonoCliente = models.IntegerField()
    direccionCliente = models.TextField()
    fechaReserva = models.DateField()
    horaReserva = models.TimeField()
    mascotaCliente = models.TextField()

class Funcionario(models.Model):
    nombreFuncionario = models.TextField()
    apellidoFuncionario = models.TextField()
    rutFuncionario = models.TextField()
    telefonoFuncionario = models.TextField()
    direccionFuncionario = models.TextField()
    contactoEmergencia = models.TextField()
    telefonoEmergencia = models.TextField()

class material(models.Model):
    nombreMaterial: models.TextField()
    fechaIngresoMaterial: models.TextField()
    numeroSerieMaterial:models.TextField()
    cantidadMaterial: models.TextField()

core/forms.py
from django import forms

veterinaria/forms.py
from django import forms 
from .models import ReservaMedica

class ReservaMedicaCreateForm(forms.ModelForm):
    class Meta:
        model = ReservaMedica
        fields = ('nombreCliente', 'apellidoCliente', 'rutCliente', 'telefonoCliente','direccionCliente','fechaReserva', 'horaReserva', 'mascotaCliente')
        widgets = {
            'nombreCliente': forms.TextInput(attrs={'class':'form-control'}),
            'apellidoCliente': forms.TextInput(attrs={'class':'form-control'}),
            'rutCliente': forms.TextInput(attrs={'class':'form-control'}),
            'telefonoCliente': forms.TextInput(attrs={'class':'form-control'}),
            'direccionCliente': forms.TextInput(attrs={'class':'form-control'}),
            'fechaReserva': forms.TextInput(attrs={'class':'form-control'}),
            'horaReserva': forms.TextInput(attrs={'class':'form-control'}),
            'mascotaCliente': forms.TextInput(attrs={'class':'form-control'})
            
        }

class ReservaMedicaUpdateForm(forms.ModelForm):
    class Meta:
        model = ReservaMedica
        fields = ('nombreCliente', 'apellidoCliente', 'rutCliente', 'telefonoCliente','direccionCliente','fechaReserva', 'horaReserva', 'mascotaCliente')
        widgets = {
            'nombreCliente': forms.TextInput(attrs={'class':'form-control'}),
            'apellidoCliente': forms.TextInput(attrs={'class':'form-control'}),
            'rutCliente': forms.TextInput(attrs={'class':'form-control'}),
            'telefonoCliente': forms.TextInput(attrs={'class':'form-control'}),
            'direccionCliente': forms.TextInput(attrs={'class':'form-control'}),
            'fechaReserva': forms.TextInput(attrs={'class':'form-control'}),
            'horaReserva': forms.TextInput(attrs={'class':'form-control'}),
            'mascotaCliente': forms.TextInput(attrs={'class':'form-control'})
            
        }

core/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={}
        return render(request, 'index.html', context)

class LoginView(View):
    def get(self, request, *args, **kwargs):
        context={}
        return render(request, 'login.html', context)

class FuncionariosView(View):
    def get(self, request, *args, **kwargs):
        context={}
        return render(request, 'funcionarios.html', context)

class InventarioView(View):
    def get(self, request, *args, **kwargs):
        context={}
        return render(request, 'inventario.html', context)

veterinaria/views.py
from django import forms
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import DeleteView, UpdateView, View
from veterinaria.forms import ReservaMedicaCreateForm, ReservaMedicaUpdateForm
from veterinaria.models import ReservaMedica


# Create your views here.
class ReservaMedicaListView(View):
    def get(self, request, *args, **kwargs):
        reservasmedicas=ReservaMedica.objects.all()
        context={
            'reservasmedicas' : reservasmedicas
        }
        
        return render(request, 'reservasmedicas.html', context)

    

class ReservaMedicaCreateView(View):
    def get(self, request):
        form = ReservaMedicaCreateForm()
        context = {
            'form':form
        }
        return render(request, 'reservasmedicascreate.html', context)

    def post(self, request):
        form = ReservaMedicaCreateForm(request.POST)
        if form.is_valid():
            nombreCliente = form.cleaned_data.get('nombreCliente')
            apellidoCliente = form.cleaned_data.get('apellidoCliente')
            rutCliente = form.cleaned_data.get('rutCliente')
            telefonoCliente = form.cleaned_data.get('telefonoCliente')
            direccionCliente = form.cleaned_data.get('direccionCliente')
            fechaReserva = form.cleaned_data.get('fechaReserva')
            horaReserva = form.cleaned_data.get('horaReserva')
            mascotaCliente = form.cleaned_data.get('mascotaCliente')
            form.save()
        return redirect('veterinaria:reservasmedicas')

class ReservaMedicaUpdateView(UpdateView):
    model = ReservaMedica
    form_class = ReservaMedicaUpdateForm
    template_name= 'reservasmedicasupdate.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('veterinaria:reservasmedicas')

class ReservaMedicaDeleteView(DeleteView):
    model = ReservaMedica
    template_name = 'reservasmedicasdelete.html'
    success_url = reverse_lazy('veterinaria:reservasmedicas')

templates/funcionarios.html
{% load static %}

{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<!DOCTYPE html>
<html lang="en" style="height: 100%;">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- ICONS ONLY -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Funcionarios</title>
</head>

<body style="height: 96%;">
    <div class="container-fluid" style="height: 100%; width: 97%; margin-top: 1%; margin-bottom: 1%;">
        <div class="row gx-4" style="height: 100%;">
            <div class="col col-xl-2 col-lg-2" style="text-align: center;">
                <div class="menu_lateral row p-3"
                    style="border-radius: 15px; height: 100%; background-color: grey; align-items: center;">
                    <div class="row">
                        <a href="{% url 'veterinaria:reservasmedicas' %}"><div class="menu"><i class="bi bi-calendar-check"></i> GESTION HORA MEDICA</div></a>
                        <a href="{% url 'veterinaria:funcionarios' %}"><div class="menu" href="#"><i class="bi bi-person-lines-fill"></i> FUNCIONARIOS</div></a>
                        <a href="{% url 'veterinaria:inventario' %}"><div class="menu" href="#"><i class="bi bi-basket"></i> INVENTARIO</div></a>
                        <a href="{% url 'veterinaria:cerrarsesion' %}"><div class="cerrar_sesion" href="#"><i class="bi bi-basket"></i> CERRAR SESION</a>
                        </div>
                    </div>

                </div>

            </div>
            <div class="col col-xl-10 col-lg-2">
                <div class="p-3" style="border-radius: 15px; height: 15%; background-color: grey;">
                    <h6 style="text-align: center; font-size: 3rem;">FUNCIONARIOS</h6>
                </div>
                <br>
                <div class="p-3" style="border-radius: 15px; height: 82%; background-color: grey;">
                    <div class="row">
                        <form class="col-6">
                            <label for="nombre">Nombre:</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                            <label for="apellido">Apellido:</label>
                            <input class="form-control" style="width: 90%;" id="email" type="text" name="email" />

                            <label for="rut">Rut:</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                            <label for="telefono">Telefono:</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                            <label for="direccion">Direccion:</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                        </form>
                        <form class="col-6">
                            <label for="nombre">Nombre Emergencia:</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                            <label for="apellido">Numero Emergencia</label>
                            <input class="form-control" style="width: 90%;" id="email" type="text" name="email" />

                            
                            <input class="me-2 mt-2 btn btn-info" type="submit" value="Crear funcionario">
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
</body>

</html>

templates/index.html
{% load static %}

{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- ICONS ONLY -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Bienvenido</title>
</head>

<body style="height: 96%;">
    <div class="container-fluid" style="height: 100%; width: 97%; margin-top: 1%; margin-bottom: 1%;">
        <div class="row gx-4" style="height: 100%;">
            <div class="col col-xl-2" style="text-align: center;" >
                <div class="menu_lateral row p-3" style="border-radius: 15px; height: 100%; background-color: grey; align-items: center;">
                    
                    <div class="row">
                        <a href="{% url 'veterinaria:reservasmedicas' %}"><div class="menu"><i class="bi bi-calendar-check"></i> GESTION HORA MEDICA</div></a>
                        <a href="{% url 'veterinaria:funcionarios' %}"><div class="menu" href="#"><i class="bi bi-person-lines-fill"></i> FUNCIONARIOS</div></a>
                        <a href="{% url 'veterinaria:inventario' %}"><div class="menu" href="#"><i class="bi bi-basket"></i> INVENTARIO</div></a>
                        <a href="{% url 'veterinaria:cerrarsesion' %}"><div class="cerrar_sesion" href="#"><i class="bi bi-basket"></i> CERRAR SESION</a>
                        </div>
                    </div>
                    
                    
                </div>

            </div>
            <div class="col col-xl-10">
                <div class="p-3" style="border-radius: 15px; background-color: grey; margin-top: 30%;"><h6 class="display-4" style="text-align: center;">BIENVENIDO</h6></div>
                
                
            </div>
        </div>
    </div>
</body>

templates/inventario.html
{% load static %}

{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en" style="height: 100%;">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- ICONS ONLY -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Document</title>
</head>

<body style="height: 96%;">
    <div class="container-fluid" style="height: 100%; width: 97%; margin-top: 1%; margin-bottom: 1%;">
        <div class="row gx-4" style="height: 100%;">
            <div class="col col-xl-2 col-lg-2" style="text-align: center;">
                <div class="menu_lateral row p-3"
                    style="border-radius: 15px; height: 100%; background-color: grey; align-items: center;">
                    <div class="row">
                        <a href="{% url 'veterinaria:reservasmedicas' %}"><div class="menu"><i class="bi bi-calendar-check"></i> GESTION HORA MEDICA</div></a>
                        <a href="{% url 'veterinaria:funcionarios' %}"><div class="menu" href="#"><i class="bi bi-person-lines-fill"></i> FUNCIONARIOS</div></a>
                        <a href="{% url 'veterinaria:inventario' %}"><div class="menu" href="#"><i class="bi bi-basket"></i> INVENTARIO</div></a>
                        <a href="{% url 'veterinaria:cerrarsesion' %}"><div class="cerrar_sesion" href="#"><i class="bi bi-basket"></i> CERRAR SESION</a>
                        </div>
                    </div>

                </div>

            </div>
            <div class="col col-xl-10 col-lg-2">
                <div class="p-3" style="border-radius: 15px; height: 15%; background-color: grey;">
                    <h6 style="text-align: center; font-size: 3rem;">INVENTARIO</h6>
                </div>
                <br>
                <div class="p-3" style="border-radius: 15px; height: 82%; background-color: grey;">
                    <div class="row">
                        <form class="col-6">
                            <label for="nombre">Material:</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                            <label for="apellido">Fecha de ingreso:</label>
                            <input class="form-control" style="width: 90%;" id="email" type="text" name="email" />

                            <label for="rut">ID o Numero de Serie</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                            <label for="telefono">Cantidad:</label>
                            <input class="form-control" style="width: 90%;" id="nombre" type="text" name="nombre" />

                            
                            <input class="me-2 mt-2 btn btn-info" type="submit" value="Crear producto">
                        </form>
                        
                    </div>

                </div>

            </div>
        </div>
    </div>
</body>

</html>

templates/login.html
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <h1 class="mt-5">Bienvenido a PETVALPO</h1>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <div class="login-form">
                <form>
                <div class="form-group">
                    <label>Usuario</label>
                    <input type="text" class="form-control" placeholder="Usuario" name="username">
                </div>
                <div class="form-group">
                    <label>Contraseña</label>
                    <input type="password" class="form-control" placeholder="Contraseña" name="password">
                </div>
                <a href="{% url 'veterinaria:home' %}" class="btn btn-info btn-flat mt-2 offset-4">Iniciar Sesion</a>
                </form>
            </div>
        </div>
    </div>
</div>

templates/reservasmedicas.html
{% load static %}

{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- ICONS ONLY -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Reservas medicas</title>
</head>

<body style="height: 96%;">
    <div class="container-fluid" style="height: 100%; width: 97%; margin-top: 1%; margin-bottom: 1%;">
        <div class="row gx-4" style="height: 100%;">
            <div class="col col-xl-2" style="text-align: center;" >
                <div class="menu_lateral row p-3" style="border-radius: 15px; height: 100%; background-color: grey; align-items: center;">
                    
                    <div class="row">
                        <a href="{% url 'veterinaria:reservasmedicas' %}"><div class="menu"><i class="bi bi-calendar-check"></i> GESTION HORA MEDICA</div></a>
                        <a href="{% url 'veterinaria:funcionarios' %}"><div class="menu" href="#"><i class="bi bi-person-lines-fill"></i> FUNCIONARIOS</div></a>
                        <a href="{% url 'veterinaria:inventario' %}"><div class="menu" href="#"><i class="bi bi-basket"></i> INVENTARIO</div></a>
                        <a href="{% url 'veterinaria:cerrarsesion' %}"><div class="cerrar_sesion" href="#"><i class="bi bi-basket"></i> CERRAR SESION</a>
                        </div>
                    </div>
                    
                    
                </div>

            </div>
            <div class="col col-xl-10">
                <div class="p-3" style="border-radius: 15px; background-color: grey; "><h6 class="display-4" style="text-align: center;">Reservas medicas</h6></div>
                
                <table class="table table-light">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">RUT</th>
                            <th scope="col">Telefono</th>
                            <th scope="col">Direccion</th>
                            <th scope="col">Fecha</th>
                            <th scope="col">Hora</th>
                            <th scope="col">Nombre mascota</th>
                            <th scope="col">Opciones</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for reservamedica in reservasmedicas %}
                            <tr>
                                <th scope="row">{{reservamedica.id}}</th>
                                <td>{{reservamedica.nombreCliente}}</td>
                                <td>{{reservamedica.apellidoCliente}}</td>
                                <td>{{reservamedica.rutCliente}}</td>
                                <td>{{reservamedica.telefonoCliente}}</td>
                                <td>{{reservamedica.direccionCliente}}</td>
                                <td>{{reservamedica.fechaReserva}}</td>
                                <td>{{reservamedica.horaReserva}}</td>
                                <td>{{reservamedica.mascotaCliente}}</td>
                                <td><a href="{% url 'veterinaria:reservasmedicasupdate' reservamedica.id%}">Actualizar reserva</a></td>
                                <td><a href="{% url 'veterinaria:reservasmedicasdelete' reservamedica.id%}">Eliminar reserva</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-md-2">
                        <a href="{% url 'veterinaria:reservasmedicascreate'%}"><div class="menu"><i class="bi bi-calendar-check"></i>Crear reserva</div></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

templates/reservasmedicascreate.html
{% load static %}

{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<link rel="stylesheet" href="{% static 'style.css' %}">


<body style="height: 96%;">
  <div class="container-fluid" style="height: 100%; width: 97%; margin-top: 1%; margin-bottom: 1%;">
      <div class="row gx-4" style="height: 100%;">
          <div class="col col-xl-2" style="text-align: center;" >
              <div class="menu_lateral row p-3" style="border-radius: 15px; height: 100%; background-color: grey; align-items: center;">
                  
                  <div class="row">
                      <a href="{% url 'veterinaria:reservasmedicas' %}"><div class="menu"><i class="bi bi-calendar-check"></i> GESTION HORA MEDICA</div></a>
                      <a href="{% url 'veterinaria:funcionarios' %}"><div class="menu" href="#"><i class="bi bi-person-lines-fill"></i> FUNCIONARIOS</div></a>
                      <a href="{% url 'veterinaria:inventario' %}"><div class="menu" href="#"><i class="bi bi-basket"></i> INVENTARIO</div></a>
                      <a href="{% url 'veterinaria:cerrarsesion' %}"><div class="cerrar_sesion" href="#"><i class="bi bi-basket"></i> CERRAR SESION</a>
                      </div>
                  </div>
                  
                  
              </div>

          </div>
          <div class="col col-xl-10">
            <div class="ms-5 mt-3">
              <div class="form-group">
                <form method="POST">
                  {% csrf_token %}
                  {{form.as_p}}
                  <input class="m-2 btn btn-success" type="submit" value="Crear reserva">
                </form>
              </div>
            </div>
          </div>
      </div>
  </div>
</body>

templates/reservasmedicasdelete.html
{% load static %}

{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<link rel="stylesheet" href="{% static 'style.css' %}">


<body style="height: 96%;">
  <div class="container-fluid" style="height: 100%; width: 97%; margin-top: 1%; margin-bottom: 1%;">
      <div class="row gx-4" style="height: 100%;">
          <div class="col col-xl-2" style="text-align: center;" >
              <div class="menu_lateral row p-3" style="border-radius: 15px; height: 100%; background-color: grey; align-items: center;">
                  
                  <div class="row">
                      <a href="{% url 'veterinaria:reservasmedicas' %}"><div class="menu"><i class="bi bi-calendar-check"></i> GESTION HORA MEDICA</div></a>
                      <a href="{% url 'veterinaria:funcionarios' %}"><div class="menu" href="#"><i class="bi bi-person-lines-fill"></i> FUNCIONARIOS</div></a>
                      <a href="{% url 'veterinaria:inventario' %}"><div class="menu" href="#"><i class="bi bi-basket"></i> INVENTARIO</div></a>
                      <a href="{% url 'veterinaria:cerrarsesion' %}"><div class="cerrar_sesion" href="#"><i class="bi bi-basket"></i> CERRAR SESION</a>
                      </div>
                  </div>
                  
                  
              </div>

          </div>
          <div class="col col-xl-10">
            <div class="ms-5 mt-3">
              <div class="form-group">
                ¿Está seguro que desea borrar la reserva?
                <form method="POST">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" class="btn btn-danger" value="Borrar">
                </form>
              </div>
            </div>
          </div>
      </div>
  </div>
</body>

templates/reservasmedicasupdate.html
{% load static %}

{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<link rel="stylesheet" href="{% static 'style.css' %}">


<body style="height: 96%;">
  <div class="container-fluid" style="height: 100%; width: 97%; margin-top: 1%; margin-bottom: 1%;">
      <div class="row gx-4" style="height: 100%;">
          <div class="col col-xl-2" style="text-align: center;" >
              <div class="menu_lateral row p-3" style="border-radius: 15px; height: 100%; background-color: grey; align-items: center;">
                  
                  <div class="row">
                      <a href="{% url 'veterinaria:reservasmedicas' %}"><div class="menu"><i class="bi bi-calendar-check"></i> GESTION HORA MEDICA</div></a>
                      <a href="{% url 'veterinaria:funcionarios' %}"><div class="menu" href="#"><i class="bi bi-person-lines-fill"></i> FUNCIONARIOS</div></a>
                      <a href="{% url 'veterinaria:inventario' %}"><div class="menu" href="#"><i class="bi bi-basket"></i> INVENTARIO</div></a>
                      <a href="{% url 'veterinaria:cerrarsesion' %}"><div class="cerrar_sesion" href="#"><i class="bi bi-basket"></i> CERRAR SESION</a>
                      </div>
                  </div>
                  
                  
              </div>

          </div>
          <div class="col col-xl-10">
            <div class="ms-5 mt-3">
              <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input class="m-2 btn btn-success" type="submit" value="Actualizar">
                </form>
              </div>
            </div>
          </div>
      </div>
  </div>
</body>